import {PERSONALITY, INTERESTS, VALUES} from './report-chart-data.mjs';

const SVG_NS='http://www.w3.org/2000/svg';
const escapeHTML=value=>String(value).replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
const signed=value=>(value>0?'+':'')+value.toFixed(1);
function svgNode(tag,attributes={},text){const node=document.createElementNS(SVG_NS,tag);for(const [key,value] of Object.entries(attributes))node.setAttribute(key,value);if(text!==undefined)node.textContent=text;return node;}
function keyboardRows(container,selector){container.addEventListener('keydown',event=>{if(!['ArrowLeft','ArrowRight','ArrowUp','ArrowDown','Home','End'].includes(event.key))return;const buttons=[...container.querySelectorAll(selector)],index=buttons.indexOf(document.activeElement);if(index<0)return;event.preventDefault();const next=event.key==='Home'?0:event.key==='End'?buttons.length-1:(index+(['ArrowLeft','ArrowUp'].includes(event.key)?-1:1)+buttons.length)%buttons.length;buttons[next].focus();buttons[next].click();});}

export function mountReportCharts(root){
  root.className='report-charts';
  root.innerHTML=`
  <article class="chart-card chart-personality" aria-labelledby="personality-chart-title">
    <div class="chart-card-head"><div><div class="chart-eyebrow">01 / Big Five personality</div><h3 id="personality-chart-title">A closer look at your responses.</h3><p class="chart-description">Choose a trait to explore the 24 keyed item scores behind its mean.</p></div><div class="chart-mode" role="group" aria-label="Response chart style"><button type="button" data-chart-mode="area" aria-pressed="true">Area</button><button type="button" data-chart-mode="bars" aria-pressed="false">Bars</button></div></div>
    <div class="trait-selector" role="group" aria-label="Choose a personality trait"></div>
    <div class="chart-summary"><div><strong id="distribution-name"></strong><p id="distribution-description"></p></div><span class="chart-sample">24 ITEMS · SYNTHETIC</span></div>
    <div class="chart-plot-wrap"><div class="chart-plot"><svg aria-hidden="true" focusable="false"></svg><div class="chart-hit-targets" role="group" aria-label="Inspect keyed score counts"></div><div class="chart-floating" aria-hidden="true"></div></div></div>
    <div class="chart-readout" role="status" aria-live="polite"><span class="readout-dot" aria-hidden="true"></span><strong id="distribution-readout"></strong><span class="readout-count" id="distribution-count"></span></div>
    <div class="chart-footer"><p>Horizontal axis: keyed score, 1–5. Vertical axis: item count. Hover, tap, or use Tab and the arrow keys to explore.</p><p id="distribution-mode-note">The stepped area joins discrete score bins. It is not a population distribution or a percentile.</p></div>
    <details class="chart-data"><summary>View chart data</summary><table><caption id="distribution-caption"></caption><thead><tr><th scope="col">Keyed score</th><th scope="col">Item count</th><th scope="col">Total items</th></tr></thead><tbody id="distribution-table"></tbody></table></details>
  </article>
  <div class="chart-pair">
    <article class="chart-card chart-interest" aria-labelledby="interest-chart-title"><div class="chart-card-head"><div><div class="chart-eyebrow">02 / The sixth lens</div><h3 id="interest-chart-title">Follow your interests.</h3><p class="chart-description">Activities you might enjoy. Six separate RIASEC scores on a 0–20 scale.</p></div></div><div class="scale-labels" aria-hidden="true"><span>0</span><span>10</span><span>20</span></div><div class="interest-rows" role="group" aria-label="Explore work interests"></div><div class="chart-insight" id="interest-insight" role="status" aria-live="polite"></div><div class="chart-footer"><p>Investigative and Artistic are tied at 18 in this example. Interests describe enjoyment, not ability or career suitability.</p></div></article>
    <article class="chart-card chart-values" aria-labelledby="values-chart-title"><div class="chart-card-head"><div><div class="chart-eyebrow">03 / The seventh lens</div><h3 id="values-chart-title">What matters to you?</h3><p class="chart-description">Ten TwIVI priorities, centered against this fictional person’s own average.</p></div></div><div class="scale-labels" aria-hidden="true"><span>−4.5</span><span>0</span><span>+4.5</span></div><div class="values-rows" role="group" aria-label="Explore personal values"></div><div class="chart-insight" id="values-insight" role="status" aria-live="polite"></div><div class="chart-footer"><p>Zero is your own mean. Left and right show lower and higher relative priority; neither is a moral grade. Two items per value limit precision.</p></div></article>
  </div>
  <div class="chart-footnote"><span class="footnote-icon" aria-hidden="true">↗</span><div><h3>Let a pattern become a small experiment.</h3><p>Try one task that involves investigating a problem and another that involves creating something. Notice what draws you in. These are prompts for reflection, not predictions about your performance.</p></div></div>`;
  const select=root.querySelector('.trait-selector'),plot=root.querySelector('.chart-plot'),svg=plot.querySelector('svg'),hits=plot.querySelector('.chart-hit-targets'),floating=plot.querySelector('.chart-floating');
  let selected=PERSONALITY[0],mode='area',activeBin=selected.counts.indexOf(Math.max(...selected.counts)),geometry=null;
  // One common count axis keeps trait switches comparable; data remain discrete.
  const ceiling=Math.ceil(Math.max(...PERSONALITY.flatMap(trait=>trait.counts))/4)*4;
  PERSONALITY.forEach(trait=>{const button=document.createElement('button');button.type='button';button.className='trait-choice';button.dataset.trait=trait.id;button.setAttribute('aria-pressed',String(trait===selected));button.setAttribute('aria-label',`${trait.name}: ${trait.mean.toFixed(2)} out of 5. Show keyed response counts.`);button.style.setProperty('--position',((trait.mean-1)/4*100)+'%');button.innerHTML=`<span class="trait-name">${escapeHTML(trait.name)}</span><span class="trait-number">${trait.mean.toFixed(2)}</span><span class="trait-unit">/ 5</span><span class="trait-track" aria-hidden="true"></span>`;button.addEventListener('click',()=>{selected=trait;activeBin=selected.counts.indexOf(Math.max(...selected.counts));select.querySelectorAll('button').forEach(b=>b.setAttribute('aria-pressed',String(b===button)));updateData();renderPlot();});select.append(button);});
  for(let index=0;index<5;index++){const button=document.createElement('button');button.type='button';button.addEventListener('pointerenter',()=>inspect(index,true));button.addEventListener('focus',()=>inspect(index,true));button.addEventListener('click',()=>inspect(index,true));hits.append(button);}
  plot.addEventListener('pointerleave',()=>floating.classList.remove('is-visible'));
  hits.addEventListener('focusout',event=>{if(!hits.contains(event.relatedTarget))floating.classList.remove('is-visible');});
  function inspect(index,showTooltip=false){activeBin=index;const count=selected.counts[index];root.querySelector('#distribution-readout').textContent=`${selected.name} · keyed score ${index+1}`;root.querySelector('#distribution-count').textContent=`${count} of 24 items`;svg.querySelectorAll('.chart-marker').forEach((point,i)=>point.dataset.active=String(i===index));const line=svg.querySelector('.chart-crosshair');if(geometry&&line){const x=geometry.left+geometry.binWidth*(index+.5);line.setAttribute('x1',x);line.setAttribute('x2',x);floating.style.left=Math.max(60,Math.min(geometry.width-60,x))+'px';floating.style.top=Math.max(0,geometry.bottom-count/ceiling*geometry.plotHeight-47)+'px';floating.textContent=`Score ${index+1} · ${count} items`;floating.classList.toggle('is-visible',showTooltip);}}
  function updateData(){root.querySelector('#distribution-name').textContent=`${selected.name} · ${selected.mean.toFixed(2)} / 5`;root.querySelector('#distribution-description').textContent=selected.description;root.querySelector('#distribution-caption').textContent=`${selected.name}: 24 synthetic keyed scores, mean ${selected.mean.toFixed(2)} / 5.`;root.querySelector('#distribution-table').innerHTML=selected.counts.map((count,index)=>`<tr><th scope="row">${index+1}</th><td>${count}</td><td>24</td></tr>`).join('');[...hits.children].forEach((button,index)=>button.setAttribute('aria-label',`${selected.name}, keyed score ${index+1}: ${selected.counts[index]} of 24 items`));}
  function renderPlot(){
    const width=Math.max(160,plot.clientWidth||960),height=width<600?220:280,left=32,right=16,top=18,bottom=height-36,plotHeight=bottom-top,binWidth=(width-left-right)/5;
    root.querySelector('#distribution-mode-note').textContent=(mode==='area'?'The stepped area joins discrete score bins.':'Each bar shows the count in a discrete score bin.')+' This is not a population distribution or a percentile.';
    geometry={width,left,bottom,plotHeight,binWidth};plot.style.height=height+'px';plot.style.aspectRatio='auto';svg.setAttribute('viewBox',`0 0 ${width} ${height}`);svg.replaceChildren();
    hits.style.left=left/width*100+'%';hits.style.right=right/width*100+'%';hits.style.top=top/height*100+'%';hits.style.bottom=(height-bottom)/height*100+'%';
    const defs=svgNode('defs'),gradient=svgNode('linearGradient',{id:'personality-area-gradient',x1:'0',y1:'0',x2:'0',y2:'1'});gradient.append(svgNode('stop',{offset:'0%','stop-color':'#478665','stop-opacity':'.46'}),svgNode('stop',{offset:'100%','stop-color':'#82ad7c','stop-opacity':'.04'}));defs.append(gradient);svg.append(defs);
    for(let tick=0;tick<=ceiling;tick+=ceiling/3){const y=bottom-tick/ceiling*plotHeight;svg.append(svgNode('line',{x1:left,x2:width-right,y1:y,y2:y,class:'chart-grid-line'}),svgNode('text',{x:left-10,y:y+4,'text-anchor':'end',class:'chart-axis-text'},String(tick)));}
    const ys=selected.counts.map(count=>bottom-count/ceiling*plotHeight);
    if(mode==='area'){let line=`M ${left} ${ys[0]}`;for(let i=0;i<5;i++){line+=` H ${left+binWidth*(i+1)}`;if(i<4)line+=` V ${ys[i+1]}`;}svg.append(svgNode('path',{d:`${line} L ${width-right} ${bottom} L ${left} ${bottom} Z`,fill:'url(#personality-area-gradient)'}),svgNode('path',{d:line,class:'chart-area-stroke'}));}
    else selected.counts.forEach((count,i)=>svg.append(svgNode('rect',{x:left+binWidth*i+binWidth*.2,y:ys[i],width:binWidth*.6,height:bottom-ys[i],rx:3,fill:'url(#personality-area-gradient)',stroke:'#326950','stroke-width':1})));
    svg.append(svgNode('line',{x1:0,x2:0,y1:top,y2:bottom,class:'chart-crosshair'}));
    selected.counts.forEach((count,i)=>{const x=left+binWidth*(i+.5);svg.append(svgNode('circle',{cx:x,cy:ys[i],r:5,class:'chart-marker'}),svgNode('text',{x,y:height-12,'text-anchor':'middle',class:'chart-axis-text'},String(i+1)));});
    inspect(activeBin);
  }
  root.querySelectorAll('[data-chart-mode]').forEach(button=>button.addEventListener('click',()=>{mode=button.dataset.chartMode;root.querySelectorAll('[data-chart-mode]').forEach(b=>b.setAttribute('aria-pressed',String(b===button)));renderPlot();}));
  keyboardRows(select,'button');keyboardRows(hits,'button');
  function populateRows(container,items,type){
    const isInterest=type==='interest',insight=root.querySelector(isInterest?'#interest-insight':'#values-insight');
    function activate(button,item){container.querySelectorAll('button').forEach(b=>b.setAttribute('aria-pressed',String(b===button)));insight.replaceChildren();const title=document.createElement('strong'),text=document.createElement('p');title.textContent=isInterest?`${item.name} · ${item.value} / 20`:`${item.name} · ${signed(item.centered)} relative priority`;text.textContent=item.description+(isInterest?'':` Raw mean: ${item.raw.toFixed(1)} / 6. This example’s overall mean: 4.0 / 6.`);insight.append(title,text);}
    items.forEach(item=>{const button=document.createElement('button');button.type='button';button.className=isInterest?'interest-row':'values-row';button.setAttribute('aria-pressed','false');const position=isInterest?item.value/20*100:(item.centered+4.5)/9*100;button.style.setProperty('--position',position+'%');button.style.setProperty('--start',Math.min(50,position)+'%');button.style.setProperty('--span',Math.abs(position-50)+'%');button.setAttribute('aria-label',isInterest?`${item.name}: ${item.value} of 20. Show activity description.`:`${item.name}: ${signed(item.centered)} relative priority; raw mean ${item.raw.toFixed(1)} of 6. Show value description.`);button.innerHTML=`<span class="chart-row-name">${escapeHTML(item.name)}</span>${isInterest?'<span class="interest-rail" aria-hidden="true"><span class="interest-fill"></span></span>':'<span class="value-rail" aria-hidden="true"><span class="value-range"></span><span class="value-point"></span></span>'}<span class="chart-row-score">${isInterest?item.value:signed(item.centered)}</span>`;button.addEventListener('click',()=>activate(button,item));container.append(button);if((isInterest&&item.id==='I')||(!isInterest&&item.name==='Self-Direction'))activate(button,item);});
    // Activate after all rows exist so exactly one is selected.
    const initial=isInterest?1:4;activate(container.children[initial],items[initial]);keyboardRows(container,'button');
  }
  populateRows(root.querySelector('.interest-rows'),INTERESTS,'interest');populateRows(root.querySelector('.values-rows'),VALUES,'values');
  updateData();renderPlot();
  // Hidden steps have zero width. Redraw when the report becomes visible or resizes.
  let lastWidth=0;const observer=new ResizeObserver(entries=>{const width=entries[0].contentRect.width;if(width>0&&width!==lastWidth){lastWidth=width;renderPlot();}});observer.observe(plot);
  return ()=>observer.disconnect();
}
