import test from 'node:test';
import assert from 'node:assert/strict';
import vm from 'node:vm';
import {readFile} from 'node:fs/promises';
import {createHash, webcrypto} from 'node:crypto';
import {MessageChannel} from 'node:worker_threads';
import {RELEASE as currentRelease} from '../website/assets/personality/v2/release.mjs';
import {AI_CACHE} from '../website/assets/personality/v1/ai-cache-config.mjs';

const workerSource = await readFile(new URL('../website/assets/personality/v2/sw.js', import.meta.url), 'utf8');
const clientSource = await readFile(new URL('../website/assets/personality/v2/offline.mjs', import.meta.url), 'utf8');
const ROOT = '/assets/personality/v2/';
const LEGACY_ROOT = '/assets/personality/v1/';
const LEGACY_DIGEST = 'a'.repeat(64);
const ORIGIN = 'https://example.test';
const ROUTES = ['/personality/prepare', '/personality/test', '/personality/review', '/personality/report', '/personality/share', '/personality/library'];
const sha = value => createHash('sha256').update(value).digest('hex');
const key = request => typeof request === 'string' ? new URL(request, ORIGIN).href : request.url;
function releaseSource(release) {
  return '// Generated by scripts/personality-release.mjs; do not edit hashes by hand.\n' +
    'const data = ' + JSON.stringify(release, null, 2) + ';\n' +
    'function freeze(value) { if (value && typeof value === "object") { Object.values(value).forEach(freeze); Object.freeze(value); } return value; }\n' +
    'export const RELEASE = freeze(data);\n';
}

function fixture() {
  const bytes = new Map([
    ['bank.mjs', Buffer.from('export const publicBank = "170 public items";')],
    ['vendor/pdf-lib/pdf-lib.mjs', Buffer.from('export const PDFDocument = "public renderer";')],
    ['fonts/report.ttf', Buffer.from('public-font-bytes')],
    ['sw.js', Buffer.from(workerSource)],
  ]);
  const publicBytes = new Map([...bytes].map(([name, body]) => [ROOT + name, body]));
  publicBytes.set(LEGACY_ROOT + 'app.mjs', Buffer.from('immutable legacy application'));
  const release = {v: 2, ready: true, legacy: {root: LEGACY_ROOT, releaseDigest: LEGACY_DIGEST}, assets: Object.fromEntries([...publicBytes].map(([name, body]) => [name, sha(body)]))};
  return {bytes: publicBytes, release};
}

function environment(customRelease) {
  const {bytes, release: fixtureRelease} = fixture(), release = customRelease ?? fixtureRelease;
  const cacheMaps = new Map(), requests = [], listeners = new Map(), activations = [];
  const controls = {offline: false, corrupt: null, failPath: null, failCommit: false, releaseChanged: false};
  const cacheObjects = new Map();
  const caches = {
    async keys() { return [...cacheMaps.keys()]; },
    async delete(name) { cacheObjects.delete(name); return cacheMaps.delete(name); },
    async open(name) {
      if (!cacheMaps.has(name)) cacheMaps.set(name, new Map());
      if (!cacheObjects.has(name)) {
        const rows = cacheMaps.get(name);
        cacheObjects.set(name, {
          async match(request) { return rows.get(key(request))?.clone(); },
          async put(request, response) {
            if (controls.failCommit && name.startsWith('personality-v2-') && !name.includes(':staging:')) throw new Error('Quota exceeded during commit');
            rows.set(key(request), response.clone());
          },
          async delete(request) { return rows.delete(key(request)); },
          async keys() { return [...rows.keys()].map(url => new Request(url)); },
        });
      }
      return cacheObjects.get(name);
    },
  };
  async function fetch(request) {
    const url = new URL(key(request));
    requests.push({url: url.href, credentials: request.credentials, cache: request.cache, referrerPolicy: request.referrerPolicy});
    if (controls.offline || controls.failPath === url.pathname) throw new Error('Network unavailable');
    if (url.pathname === ROOT + 'release.mjs') return new Response(releaseSource(release) + (controls.releaseChanged ? '\n' : ''), {headers: {'Content-Type': 'text/javascript'}});
    if (url.pathname.startsWith(ROOT) || url.pathname.startsWith(LEGACY_ROOT)) {
      const body = bytes.get(url.pathname);
      if (!body) return new Response('Not found', {status: 404});
      return new Response(controls.corrupt === url.pathname ? Buffer.from('wrong bytes') : body, {headers: {'Content-Type': 'application/octet-stream'}});
    }
    if (ROUTES.includes(url.pathname)) return new Response(`<html>Public shell: ${url.pathname}${url.search}</html>`, {headers: {'Content-Type': 'text/html; charset=utf-8'}});
    return new Response('Other public page');
  }
  const context = vm.createContext({
    __release: release, __ai: AI_CACHE, __releaseSource: releaseSource, crypto: webcrypto, URL, Request, Response, TextEncoder, Uint8Array,
    caches, fetch, console,
    self: {location: {origin: ORIGIN}, addEventListener: (type, listener) => listeners.set(type, listener),
      skipWaiting: async () => { activations.push('skipWaiting'); }, clients: {claim: async () => {}}},
  });
  assert(workerSource.startsWith("import {RELEASE} from '/assets/personality/v2/release.mjs';"));
  vm.runInContext(workerSource.replace(/^import[^\n]+\n/, 'const RELEASE = __release;\n').replace(/^import \{AI_CACHE\}[^\n]+\n/m,'const AI_CACHE = __ai;\n').replace(/^import \{releaseSource\}[^\n]+\n/m, 'const releaseSource = __releaseSource;\n'), context, {filename: 'personality-worker.js'});
  const digest = sha(JSON.stringify(release));
  async function lifecycle(type) {
    let promise;
    listeners.get(type)({waitUntil(value) { promise = value; }});
    await promise;
  }
  async function install({source = ORIGIN + '/personality/library', requestedDigest = digest} = {}) {
    const messages = []; let promise;
    listeners.get('message')({data: {type: 'INSTALL_RELEASE', releaseDigest: requestedDigest}, source: {url: source},
      ports: [{postMessage(message) { messages.push(message); }}], waitUntil(value) { promise = value; }});
    await promise;
    return messages;
  }
  async function dispatch(url, {mode = 'navigate', method = 'GET'} = {}) {
    let result;
    listeners.get('fetch')({request: {url: new URL(url, ORIGIN).href, method, mode}, respondWith(value) { result = value; }});
    return result ? await result : undefined;
  }
  return {context, cacheMaps, caches, requests, controls, release, digest, lifecycle, install, dispatch, activations};
}

test('install and activation do not preload files or alter unrelated caches', async () => {
  const env = environment();
  const root = await env.caches.open('engmanager-v5'); await root.put('/offline.html', new Response('blog offline'));
  await env.lifecycle('install'); await env.lifecycle('activate');
  assert.equal(env.requests.length, 0);
  assert.equal(env.activations.length, 0, 'An update must not evict the current worker before explicit installation.');
  assert.deepEqual(await env.caches.keys(), ['engmanager-v5']);
});

test('optional AI runtime requires its pinned ready marker and never joins the base install',async()=>{
 const env=environment();await env.install();assert(env.requests.every(r=>!r.url.includes('/ai/')));
 const path=AI_CACHE.paths.find(p=>p.endsWith('runtime.mjs')),cache=await env.caches.open(AI_CACHE.name);
 await cache.put(path,new Response('installed runtime'));env.controls.offline=true;
 await assert.rejects(()=>env.dispatch(path,{mode:'cors'}),/Network unavailable/);
 await cache.put(AI_CACHE.ready,new Response('wrong digest'));
 await assert.rejects(()=>env.dispatch(path,{mode:'cors'}),/Network unavailable/);
 await cache.put(AI_CACHE.ready,new Response(AI_CACHE.digest));
 assert.equal(await(await env.dispatch(path,{mode:'cors'})).text(),'installed runtime');
 assert.equal(await env.dispatch(path+'?private=answers',{mode:'cors'}),undefined);
 assert.equal(await env.dispatch('/personality/__local-ai/model-index-v1',{mode:'cors'}),undefined);
 assert.equal(await env.dispatch('/assets/personality/ai/v1/unknown.wasm',{mode:'cors'}),undefined);
});

test('explicit install verifies all public assets, six clean shells, and separately pinned manifest bytes', async () => {
  const env = environment(), messages = await env.install();
  const ready = messages.at(-1);
  assert.equal(ready.type, 'OFFLINE_READY'); assert.equal(ready.routes, 6); assert.equal(ready.assets, 6);
  assert.equal(ready.cacheName, `personality-v2-${env.digest}`);
  assert.deepEqual(env.activations, ['skipWaiting']);
  const names = await env.caches.keys(); assert.deepEqual(names, [ready.cacheName]);
  const rows = env.cacheMaps.get(ready.cacheName);
  assert.equal(rows.size, 13); // Five hashed assets across both versions, manifest, six routes, marker.
  assert([...rows.keys()].every(url => !new URL(url).search && !new URL(url).hash));
  for (const route of ROUTES) assert(rows.has(ORIGIN + route));
  assert(rows.has(ORIGIN + ROOT + 'vendor/pdf-lib/pdf-lib.mjs'));
  assert(rows.has(ORIGIN + ROOT + 'fonts/report.ttf'));
  assert(env.requests.every(request => request.credentials === 'omit' && request.referrerPolicy === 'no-referrer' && request.cache === 'reload'));
  const before = env.requests.length;
  assert.equal((await env.install()).at(-1).type, 'OFFLINE_READY');
  assert.equal(env.requests.length, before, 'A complete immutable release need not be downloaded twice.');
});

test('reduced article document may install after SPA navigation without caching the article', async () => {
  const env = environment();
  // Chrome can expose the original document URL in MessageEvent.source even
  // after the application pushes /personality/library into browser history.
  const messages = await env.install({source: ORIGIN + '/articles/big-personality'});
  assert.equal(messages.at(-1).type, 'OFFLINE_READY');
  assert.equal(messages.at(-1).routes, 6);
  const keys = [...env.cacheMaps.values()].flatMap(rows => [...rows.keys()]);
  assert(!keys.some(url => new URL(url).pathname === '/articles/big-personality'));
  assert(!env.requests.some(request => new URL(request.url).pathname === '/articles/big-personality'));
});

test('hash mismatch or changed release module never publishes a partial release', async () => {
  for (const failure of ['asset', 'manifest']) {
    const env = environment();
    const root = await env.caches.open('engmanager-v5'); await root.put('/offline.html', new Response('retained'));
    if (failure === 'asset') env.controls.corrupt = ROOT + 'bank.mjs';
    else env.controls.releaseChanged = true;
    const messages = await env.install();
    assert.equal(messages.at(-1).type, 'OFFLINE_ERROR');
    assert.deepEqual(await env.caches.keys(), ['engmanager-v5']);
    assert.equal(await (await root.match('/offline.html')).text(), 'retained');
  }
});

test('network failure and commit quota failure clean staging without deleting another release', async () => {
  for (const failure of ['network', 'quota']) {
    const env = environment();
    const old = await env.caches.open('personality-v1-an-older-release'); await old.put('/personality/prepare', new Response('old shell'));
    if (failure === 'network') env.controls.failPath = '/personality/share';
    else env.controls.failCommit = true;
    assert.equal((await env.install()).at(-1).type, 'OFFLINE_ERROR');
    assert.deepEqual(await env.caches.keys(), ['personality-v1-an-older-release']);
    assert.equal(await (await old.match('/personality/prepare')).text(), 'old shell');
  }
});

test('query navigation is never cached and offline replay reads the matching clean route', async () => {
  const env = environment();
  await env.install();
  const keysBefore = [...env.cacheMaps.values()].flatMap(map => [...map.keys()]);
  const query = '/personality/report?r=PRIVATE-SUMMARY';
  const online = await env.dispatch(query);
  assert((await online.text()).includes('?r=PRIVATE-SUMMARY'));
  assert.deepEqual([...env.cacheMaps.values()].flatMap(map => [...map.keys()]), keysBefore);
  env.controls.offline = true;
  const offline = await env.dispatch(query);
  assert.equal(await offline.text(), '<html>Public shell: /personality/report</html>');
  for (const route of ROUTES) assert.equal((await env.dispatch(route)).status, 200);
  assert(![...env.cacheMaps.values()].flatMap(map => [...map.keys()]).some(url => url.includes('PRIVATE-SUMMARY')));
});

test('public assets are cache-first only from a fully installed release', async () => {
  const env = environment();
  await env.dispatch(ROOT + 'bank.mjs', {mode: 'cors'});
  assert.deepEqual(await env.caches.keys(), [], 'Online assets do not silently trigger a partial install.');
  await env.install(); env.controls.offline = true;
  const before = env.requests.length;
  assert.equal((await env.dispatch(ROOT + 'bank.mjs', {mode: 'cors'})).status, 200);
  assert.equal(env.requests.length, before);
  assert.equal(await env.dispatch(ROOT + 'bank.mjs?answer=5', {mode: 'cors'}), undefined);
  assert.equal(await env.dispatch('/personality/unknown'), undefined);
  assert.equal(await env.dispatch('https://other.test/personality/report'), undefined);
  assert.equal(await env.dispatch('/personality/report', {method: 'POST'}), undefined);
});

test('first offline visit is an honest 503 and foreign/stale install requests cannot write caches', async () => {
  const env = environment(); env.controls.offline = true;
  const response = await env.dispatch('/personality/test?r=not-cached');
  assert.equal(response.status, 503); assert((await response.text()).includes('not available offline yet'));
  env.controls.offline = false;
  for (const options of [{source: 'https://other.test/personality/library'}, {source: ORIGIN + '/articles/other'}, {requestedDigest: '0'.repeat(64)}]) {
    assert.equal((await env.install(options)).at(-1).type, 'OFFLINE_ERROR');
  }
  assert.deepEqual(await env.caches.keys(), []);
});

test('worker reconstruction matches the actual generated release file exactly', async () => {
  const env = environment(currentRelease);
  const expected = vm.runInContext('expectedReleaseSource()', env.context);
  const actual = await readFile(new URL('../website/assets/personality/v2/release.mjs', import.meta.url), 'utf8');
  assert.equal(expected, actual);
});

test('a frozen v1 installer receives its own digest after the complete compatible v2 installation', async () => {
  const env = environment();
  const old = await env.caches.open(`personality-v1-${LEGACY_DIGEST}`);
  await old.put('/personality/.offline-ready-v1', new Response('ready'));
  await old.put('/personality/report', new Response('original legacy shell'));
  const messages = await env.install({requestedDigest: LEGACY_DIGEST});
  assert.equal(messages.at(-1).type, 'OFFLINE_READY');
  assert(messages.every(message => message.releaseDigest === LEGACY_DIGEST));
  assert.equal(messages.at(-1).cacheName, `personality-v2-${env.digest}`);
  assert.equal(await (await old.match('/personality/report')).text(), 'original legacy shell');
  env.controls.offline = true;
  assert.equal(await (await env.dispatch(LEGACY_ROOT + 'app.mjs', {mode: 'cors'})).text(), 'immutable legacy application');
  assert.equal(await (await env.dispatch('/personality/report#s=legacy')).text(), '<html>Public shell: /personality/report</html>');
  const keys = [...env.cacheMaps.values()].flatMap(rows => [...rows.keys()]);
  assert(keys.every(url => !new URL(url).search && !new URL(url).hash));
});

test('the compatible worker can fall back to the exact retained v1 cache without modifying it', async () => {
  const env = environment();
  const old = await env.caches.open(`personality-v1-${LEGACY_DIGEST}`);
  await old.put('/personality/report', new Response('original legacy shell'));
  await old.put(LEGACY_ROOT + 'app.mjs', new Response('original legacy app'));
  env.controls.offline = true;
  assert.equal((await env.dispatch('/personality/report')).status, 503, 'Uncommitted legacy caches are ignored.');
  await old.put('/personality/.offline-ready-v1', new Response('ready'));
  const before = await old.keys();
  assert.equal(await (await env.dispatch('/personality/report?r=summary')).text(), 'original legacy shell');
  assert.equal(await (await env.dispatch(LEGACY_ROOT + 'app.mjs', {mode: 'cors'})).text(), 'original legacy app');
  assert.deepEqual((await old.keys()).map(item => item.url), before.map(item => item.url));
  assert.deepEqual(await env.caches.keys(), [`personality-v1-${LEGACY_DIGEST}`]);
});

test('client module is inert until clicked, registers exact module scope, and awaits ready acknowledgement', async () => {
  const {release} = fixture(), registrations = [], messages = [], progress = [];
  const worker = {state: 'activated', addEventListener() {}, removeEventListener() {}, postMessage(data, [port]) {
    messages.push(data);
    port.postMessage({type: 'OFFLINE_PROGRESS', releaseDigest: data.releaseDigest, completed: 1, total: 11});
    setTimeout(() => { port.postMessage({type: 'OFFLINE_READY', releaseDigest: data.releaseDigest, cacheName: 'installed', assets: 5, routes: 6}); port.close(); }, 10);
  }};
  const context = vm.createContext({__release: release, crypto: webcrypto, TextEncoder, Uint8Array, Date, Promise,
    isSecureContext: true, caches: {}, MessageChannel, setTimeout, clearTimeout,
    navigator: {serviceWorker: {async register(url, options) { registrations.push({url, options}); return {active: worker}; }}}});
  vm.runInContext(clientSource.replace(/^import[^\n]+\n/, 'const RELEASE = __release;\n').replace('export function installOffline', 'function installOffline'), context);
  assert.equal(registrations.length, 0);
  const first = context.installOffline({onProgress: value => progress.push(value)}), second = context.installOffline();
  assert.equal(first, second);
  const result = await first;
  assert.equal(result.routes, 6); assert.equal(result.assets, 5);
  assert.equal(registrations.length, 1); assert.equal(registrations[0].url, '/personality/sw.js');
  assert.equal(registrations[0].options.scope, '/personality/'); assert.equal(registrations[0].options.type, 'module');
  assert.equal(registrations[0].options.updateViaCache, 'none');
  assert.equal(messages.length, 1); assert.deepEqual(Object.keys(messages[0]), ['type', 'releaseDigest']);
  assert.equal(messages[0].releaseDigest, sha(JSON.stringify(release)));
  assert.equal(progress.length, 1);
});

test('waiting worker installs before takeover and client waits for activation after cache-ready', async () => {
  const {release} = fixture(), listeners = new Set();
  let listenCount = 0, enteredActivation;
  const activationPhase = new Promise(resolve => { enteredActivation = resolve; });
  const worker = {state: 'installed', addEventListener(type, listener) {
    listeners.add(listener); listenCount++; if (listenCount === 2) enteredActivation();
  }, removeEventListener(type, listener) { listeners.delete(listener); }, postMessage(data, [port]) {
    port.postMessage({type: 'OFFLINE_READY', releaseDigest: data.releaseDigest, cacheName: 'verified', assets: 5, routes: 6});
    port.close();
  }};
  const context = vm.createContext({__release: release, crypto: webcrypto, TextEncoder, Uint8Array, Date, Promise,
    isSecureContext: true, caches: {}, MessageChannel, setTimeout, clearTimeout,
    navigator: {serviceWorker: {async register() { return {waiting: worker, active: {state: 'activated'}}; }}}});
  vm.runInContext(clientSource.replace(/^import[^\n]+\n/, 'const RELEASE = __release;\n').replace('export function installOffline', 'function installOffline'), context);
  let settled = false;
  const installed = context.installOffline().then(result => { settled = true; return result; });
  await activationPhase;
  assert.equal(settled, false); assert.equal(worker.state, 'installed');
  worker.state = 'activated'; for (const listener of [...listeners]) listener();
  assert.equal((await installed).cacheName, 'verified'); assert.equal(settled, true);
});
