#!/usr/bin/env node
// Rebuild only before publishing an immutable v1 release. Published source paths
// and manifest hashes must be retained; substantive later versions use /v2/.
import {readFile, writeFile, readdir} from 'node:fs/promises';
import {fileURLToPath, pathToFileURL} from 'node:url';
import path from 'node:path';
import {createHash} from 'node:crypto';

const root = fileURLToPath(new URL('../website/assets/personality/v1/', import.meta.url));
const allowIncomplete = process.argv.includes('--allow-incomplete');
const digest = value => createHash('sha256').update(value).digest('hex');
// Copy only the tiny pinned cache routing metadata into the base release.
// Runtime binaries and user-imported model weights are separate installations.
const {AI_ASSETS,AI_RUNTIME_CACHE,AI_MANIFEST_DIGEST}=await import('../website/assets/personality/ai/v1/assets.mjs');
await writeFile(path.join(root,'ai-cache-config.mjs'),'// Generated optional-runtime routing metadata; no model bytes.\nexport const AI_CACHE = Object.freeze('+JSON.stringify({name:AI_RUNTIME_CACHE,digest:AI_MANIFEST_DIGEST,ready:'/assets/personality/ai/v1/__runtime-ready',paths:[...AI_ASSETS.map(a=>a.path),'/assets/personality/ai/v1/assets.mjs']})+');\n');
const {BANK} = await import(pathToFileURL(path.join(root, 'bank.mjs')));
const assets = {};
async function walk(directory, prefix = '') {
  for (const entry of (await readdir(directory, {withFileTypes: true})).sort((a, b) => a.name.localeCompare(b.name))) {
    const relative = prefix + entry.name;
    if (entry.isDirectory()) await walk(path.join(directory, entry.name), `${relative}/`);
    else if (entry.isFile() && entry.name !== 'release.mjs') assets[relative] = digest(await readFile(path.join(directory, entry.name)));
  }
}
await walk(root);
const required = ['app.mjs', 'style.css', 'bank.mjs', 'core.mjs', 'store.mjs', 'share.mjs', 'report-content.mjs', 'report.mjs', 'charts.mjs', 'charts.css', 'pdf.mjs', 'offline.mjs', 'sw.js', 'enhancement.mjs', 'enhancement-share.mjs', 'reflection-ui.mjs', 'ai-cache-config.mjs'];
const missing = required.filter(file => !assets[file]);
if (missing.length && !allowIncomplete) throw new Error(`Release incomplete: ${missing.join(', ')}`);
let blockIds = [];
if (assets['report-content.mjs']) {
  const content = await import(pathToFileURL(path.join(root, 'report-content.mjs')));
  blockIds = [...(content.BLOCK_IDS ?? content.EXPERIMENTS?.map(item => item.id) ?? [])].sort();
}
const contentFiles = ['report-content.mjs', 'enhancement.mjs'];
const templateFiles = ['report.mjs', 'charts.mjs', 'pdf.mjs'];
const fileDigest = files => digest(JSON.stringify(files.map(file => [file, assets[file] ?? null])));
const aliases = ['ipip-neo-120', 'onet-mini-ip-30', 'twivi-20'];
const modules = ['big5', 'interests', 'values'];
const release = {
  v: 1,
  releases: {
    instruments: modules.map((module, index) => [aliases[index], BANK.instrumentVersions[index], digest(JSON.stringify({
      administration: BANK.modules.find(item => item.id === module), items: BANK.items.filter(item => item.module === module),
    }))]),
    content: ['content-v1', fileDigest(contentFiles)],
    scoring: ['score-v1', assets['core.mjs'] ?? digest('incomplete')],
    template: ['report-v1', fileDigest(templateFiles)],
    order: ['source-v1', digest(JSON.stringify(BANK.items.map(item => [item.id, item.module, item.slot])))],
  },
  blockIds,
  ready: missing.length === 0,
  assets,
};
const output = '// Generated by scripts/personality-release.mjs; do not edit hashes by hand.\n' +
  'const data = ' + JSON.stringify(release, null, 2) + ';\n' +
  'function freeze(value) { if (value && typeof value === "object") { Object.values(value).forEach(freeze); Object.freeze(value); } return value; }\n' +
  'export const RELEASE = freeze(data);\n';
await writeFile(path.join(root, 'release.mjs'), output);
console.log(`Personality release: ${Object.keys(assets).length} public assets; ${release.ready ? 'complete' : 'incomplete development manifest'}.`);
